# Generated by Django 5.2.1 on 2025-07-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_user_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.category'),
        ),
    ]
